### PR TITLE
Consider articles without lastPublishDateTimes as not proper articles.

### PR DESCRIPTION
**Pull request by matthew-andrews**
We had to fix this in `ft-app-api` in a similar way.

http://git.svc.ft.com:8080/projects/FTA/repos/ft-app-api/browse/app/classes/ContentObjects/Article?at=ae293cdcc2b05842c5a22d3afa5c8ac9a184a5b9#42

[Note the date of that commit — 25th March 2013]

It makes me sad that after all these years we are fixing this again in the front end when it should have been fixed upstream.  Grr. >:(.

// cc @martingartonft

### CODE REVIEW

**Comment by commuterjoy** [comment]
We should have flags around this with expiry dates. If nobody upstream can be bothered to fix it in 3 months then I don't see why we should be bothered to implement it.

**Comment by matthew-andrews** [comment]
@commuterjoy It was causing this error:- https://app.getsentry.com/nextftcom/ft-next-dobi/group/51302502/

**Comment by matthew-andrews** [comment]
although i do agree with you in principle…

**Comment by matthew-andrews** [comment]
in capi v2 this is fixed

**Pull request merged**
